services:
  db:
    image: mysql:8.4.3
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: dualizadb
    volumes:
      - ./mysql:/var/lib/mysql
